export const roles: GameRoleId[] = [
  "rent-lord",
  "wall-street-wolf",
  // "private-buyer",
  "auction-strategist",
  "card-stealer",
  // "the-constructor",
  "financer",
]
export const botConstants = {
  rollAgainThreshold: 100,
  get10PercentFromAllPlayersThresholdPerPlayer: 500,
  get10PercentFromPlayerThreshold: 1000,
  get20PercentFromPlayerThreshold: 800,
  propertyTaxThreshold: { 2: 9, 3: 7, 4: 5 },
  getInterestThreshold: {
    mainMoney: 800,
    stockMoney: 0,
  },
  safePlayFactor: 1,
}
export const botNames = [
  "John",
  "Jenny",
  "Tom",
  "Jack",
  "Harry",
  "Emma",
  "Bob",
  "Alice",
  "Charlie",
  "Diana",
  "Ethan",
  "Fiona",
  "George",
  "Hannah",
  "Isaac",
  "Julia",
  "Kevin",
  "Liam",
  "Mia",
  "Noah",
  "Olivia",
  "Patrick",
  "Quinn",
  "Ryan",
  "Sarah",
  "Thomas",
  "Uma",
  "Victor",
  "Wendy",
  "Xavier",
  "Yara",
  "Zane",
]
